### ISSUE TITLE
Fix dependency badge in Readme

### ISSUE THREAD

**Issue by philihp** [philihp/sort-unwind#52]
The dependency badge with David seems broken. Find reliable alternative. I liked that one because it only tracked libraries I depended upon directly.

**Comment by dNhunter3107** [comment]
I want to contribute

**Comment by salilbc** [comment]
https://github.com/philihp/sort-unwind/pull/53

**Comment by philihp** [comment]
Accepted #53 because it fixes the image, but I'd still like to replace David with something else more reliable

**Comment by philihp** [comment]
Resolved with b8a1347
