### ISSUE TITLE
Why the Ramda pipeline?

### ISSUE THREAD

**Issue by CrossEye** [philihp/sort-unwind#7]
It seems to me that this is much simpler than the Ramda version you've created:

```js
const unwind = (ranks, xs) => [
  ranks .map (x => ranks [ranks [x]]), 
  ranks .map ((_, i) => xs [ranks .indexOf (i)])
]
```

As far as I can tell, it [works the same][rr].

Am I missing something?

(BTW, I'm one of the founders of Ramda and a big fan, but this version seems much simpler.)

  [rr]: https://tinyurl.com/y9y44x2w

**Comment by philihp** [comment]
Forgive the delay in response, and thank you for thinking about this!

I do appreciate that that way is shorter, although wouldn't that way run in O(n^2) time because of the map on indexOf?

Additionally, it fails for this test case:

```js
const unwind = (ranks, xs) => [
  ranks .map ((_, i) => xs [ranks .indexOf (i)]),
  ranks .map (x => ranks [ranks [x]])
]

const src = ['b','c','a']
const rank = [1, 2, 0]

const [mid, derank] = unwind(rank, src)
const [dst, demid] = unwind(derank, mid)

console.log({src, rank})
console.log({mid, derank})
console.log({dst, demid})
```
comes back with
```json
{"src":["b","c","a"],"rank":[1,2,0]}
{"mid":["a","b","c"],"derank":[0,1,2]}
{"dst":["a","b","c"],"demid":[0,1,2]}
```

**Comment by philihp** [comment]
Forgive the delay in response, and thank you for thinking about this!

I do appreciate that that way is shorter, although wouldn't that way run in O(n^2) time because of the map on indexOf?

Additionally, it fails for this test case:

```js
const unwind = (ranks, xs) => [
  ranks .map ((_, i) => xs [ranks .indexOf (i)]),
  ranks .map (x => ranks [ranks [x]])
]

const src = ['b','c','a']
const rank = [1, 2, 0]

const [mid, desrc] = unwind(rank, src)
const [dst, demid] = unwind(desrc, mid)

console.log({src, rank})
console.log({mid, desrc})
console.log({dst, demid})
```
comes back with
```js
{"src":["b","c","a"],"rank":[1,2,0]}
{"mid":["a","b","c"],"desrc":[0,1,2]}
{"dst":["a","b","c"],"demid":[0,1,2]}
// should be
// {"dst":["b","c","a"],"demid":[1,2,0]}
```

**Comment by CrossEye** [comment]
Well, I clearly missed something there, and might look at it again, but please ignore me here!

**Comment by CrossEye** [comment]
Perhaps https://tinyurl.com/ygcdeahg, but it's not really important.

**Comment by philihp** [comment]
This then fails: [`unwind([0, 1], ['a', 'b'])`](https://ramdajs.com/repl/#?console%20.clear%20%28%29%0A%0Aconst%20unwind%20%3D%20%28ranks%2C%20xs%29%20%3D%3E%20%5B%0A%20%20ranks%20.map%20%28%28_%2C%20i%29%20%3D%3E%20xs%20%5Branks%20.indexOf%20%28i%29%5D%29%2C%0A%20%20ranks%20.map%20%28x%20%3D%3E%20ranks%20%5Bx%5D%29%0A%5D%0A%0Aconst%20src%20%3D%20%5B%27a%27%2C%27b%27%5D%0Aconst%20rank%20%3D%20%5B0%2C%201%5D%20%0A%0Aconst%20%5Bmid%2C%20desrc%5D%20%3D%20unwind%20%28rank%2C%20src%29%0Aconst%20%5Bdst%2C%20demid%5D%20%3D%20unwind%20%28desrc%2C%20mid%29%0A%0Aconsole.log%28%7Bsrc%2C%20rank%7D%29%0Aconsole.log%20%28%7Bmid%2C%20desrc%7D%29%0Aconsole.log%28%7Bdst%2C%20demid%7D%29)

I think we're close though! [this feature](https://github.com/philihp/sort-unwind/blob/main/src/__tests__/index.test.js#L75-L81) also fails, but I'm okay with killing that and the uncurry'ing at the next major version update in order to remove the Ramda dependency. I'd like to keep this running in linear time, though, by precomputing indexOf, as below

```js
const unwind = (ranks, xs) => {
  const indexer = ranks.reduce( (accum, e, i) => (accum[e]=i, accum), {})
  return [
    ranks .map ((_, i) => xs [indexer[i]]),
    ranks .map (x => ranks [x])
  ]
}
```

**Comment by philihp** [comment]
These tests will run on PRs, if you'd like to submit one! :)

**Comment by CrossEye** [comment]
I don't see the failure in that case.  But it does break the feature you're looking at.

I wasn't bringing this up to suggest you remove the Ramda dependency.  I simply thought the implementation was doing more work and contained more complexity than necessary.

Obviously, it would not be hard to remove the Ramda dependency.  The only things for which there isn't already a trivial vanilla implementation are `uncurryN` and `transpose`.  The former is easy to bake in for a two-argument function, and the latter is a one-liner.  For instance, https://tinyurl.com/yh3rwxe5.  But this is no longer as simple as the Ramda pipeline, and my rationale for suggesting it no longer applies.  Of course, removing a dependency is always a nice goal on its own.

**Comment by philihp** [comment]
Oops, my mistake. I meant to say:

```js
const unwind = (ranks, xs) => {
  const indexer = ranks.reduce( (accum, e, i) => (accum[e]=i, accum), {})
  return [
    ranks .map ((_, i) => xs [indexer[i]]),
    ranks .map (x => ranks [x])
  ]
}

unwind([1, 0], ['a', 'b'])
```
returns
```js
[['b', 'a'], [0, 1]]
```
and should return
```js
[['b', 'a'], [1, 0]]
```

**Comment by CrossEye** [comment]
Ahh.

Well it looks like my simplifications simply won't work.

If you want to remove the Ramda dependency, my previous suggestion might work.  But that's a different question than I was asking.

```js
const _transpose = (xs) => 
  xs [0] .map ((_, i) => xs .map (r => r [i]))

const unwind = (rank, xs) => {
  const fn = (xs) => _transpose (
    xs .map ((x, i) => [rank [i], [x, i]])
       .sort (([a], [b]) => a - b)
       .map (([_, x])=> x)
  )
  return Array.isArray(xs) ? fn (xs) : fn
}
```
